import random

def adivina_el_número(x):

    print("============================")
    print("  Welcome to the game  ")
    print("============================")
    print(" Your goal is to guess the number generated by the computer")

    número_aleatorio = random.randint(1, x) # número aleatorio entre 1 y x.

    # La predicción es 0 inicialmente para que no coincida con el número aleatorio. 
    predicción = 0

    # Continuar prediciendo el número hasta que la predicción sea correcta.
    while predicción != número_aleatorio:
        # El usuario ingresa un número.
        predicción = int(input(f'Guess a number between 1 and {x}: '))
        # Si el número es menor que el número aleatorio, se 
        # muestra un mensaje.
        if predicción < número_aleatorio:
            print('Try again, this number is too small')
        # Si el número es mayor que el número aleatorio, se
        # muestra un mensaje.
        elif predicción > número_aleatorio:
            print('Try again, this number is too big')

    # El ciclo o bucle se detiene cuando el usuario adivina el número
    # correctamente y se muestra un mensaje final.
    print(f'Yey u guessed the number {número_aleatorio} correctly')

# Llamar a la función
adivina_el_número(10)